import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Componets/Header";
import Footer from "@/Componets/Footer";
// import "aos/dist/aos.css";
import { CartProvider } from "./context/cardContext";

export const metadata: Metadata = {
  title: "Dough & Delight",
  description: "Home bakery website",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Header />
          {children}
          <Footer />
        </CartProvider>
        <CartProvider>
          <Header />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // export const metadata: Metadata = {
// //   title: "Dough & Delight",
// //   description: "Generated by create next app",
// // };

// export const metadata = {
//   title: "Dough & Delight",
//   description: "Home bakery website",
//   // todo
//   // icons: {
//   //   icon: "../public/favicon.ico",
//   // },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
